# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
${custom.hostname}\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$status\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[⌘](bold green)"  
error_symbol = "[⌘](bold red)"

[username]
show_always = true
aliases = { "aditya" = "Aditya", "adityasanka" = "Aditya" }
format = '[$user]($style) @ '

[custom.hostname]
description = 'Custom hostname'
when = true
command = "echo ${MACHINE:- Macbook}"
format = '[$symbol($output)]($style) in '

[git_branch]
symbol = " "
