# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$status\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "[⌘](bold green)"  
error_symbol = "[⌘](bold red)"

[git_branch]
symbol = " "
