#+TITLE: Getting Started With Emacs
#+STARTUP: overview

** Installing Emacs

  Emacs is included in Mac OS X, but is usually an old version. It is recommended that you use the latest stable version. To get the latest and greatest features, there are community built packages like [[https://emacsformacosx.com/][Emacs For OS X]] or [[https://formulae.brew.sh/formula/emacs][Homebrew]] that are easy to install.

** Use alternative icon

  I like minimal icons. You can change the Emacs GUI icon using the following steps.

  + Download the icns file from [[https://emacs.sexy/img/Emacs.icns][emacs.sexy]].
  + Open Finder, go to Applications, and right click Emacs to Show Package Contents, then navigate to =Contents - Resources=.
  + Replace the existing Emacs.icns file with the new one.
  + One more thing ...
    - In a new Finder window, go to Applications, right click Emacs and click =Get Info=.
    - Then from the other Finder where you have the new Emacs.icns file, DRAG it to the TOP LEFT small icon in the Get Info window. 
  
